services:
  - mongo:latest

stages:
  - test
  - deploy

test:
  stage: test
  image: bhdouglass/openstore-ci
  before_script:
    - npm install
  script:
    - npm run lint
    - npm run lint:json
    - npm run test:ci
    - npm run build

deploy:
  stage: deploy
  only:
    - master
  image: bhdouglass/openstore-ci
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - VERSION=$(date +"%Y-%m-%d_%H-%M-%S")
    - echo $VERSION
    - npm install
    - npm run build
    - rsync -av --delete --exclude node_modules --exclude ".*" . root@ssh.open-store.io:/srv/openstore-api/$VERSION
    - ssh root@ssh.open-store.io "/srv/openstore-api/$VERSION/deploy/post-deploy.sh $VERSION"

deploy_staging:
  stage: deploy
  only:
    - staging
  image: bhdouglass/openstore-ci
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - ENV=-staging
    - VERSION=$(date +"%Y-%m-%d_%H-%M-%S")
    - echo $VERSION
    - npm install
    - npm run build
    - rsync -av --delete --exclude node_modules --exclude ".*" . root@ssh.open-store.io:/srv/openstore-api$ENV/$VERSION
    - ssh root@ssh.open-store.io "/srv/openstore-api$ENV/$VERSION/deploy/post-deploy.sh $VERSION $ENV"

sast:
  variables:
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, po, deploy
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, flawfinder, gosec, kubesec,
      phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
